<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {


        $this->call([
            PermissionsSeeder::class,
            RolesSeeder::class,
            
        ]);
        // Assign permissions to roles
        $roles = [
            'Direction Admin' => [
                'Create Dossier_Justice',
                'Edit Dossier_Justice',
                'Delete Dossier_Justice',
                'Preview Dossier_Justice',
                'List Dossier_Justice',
                'Create Partie_Adverse',
                'Edit Partie_Adverse',
                'Delete Partie_Adverse',
                'List Partie_Adverse',
                'Preview Partie_Adverse',
                'Create Audience',
                'Edit Audience',
                'Delete Audience',
                'List Audience',
                'Preview Audience',
                'Create Avocat',
                'Delete Avocat',
                'Edit Avocat',
                'Preview Avocat',
                'List Avocat',
                'Create Cour',
                'Edit Cour',
                'Delete Cour',
                'Preview Cour',
                'List Cour',
                'Create User',
                'Edit User',
                'Delete User',
                'Preview User',
                'List User',
                'Create Files',
                'Delete Files',
                'Edit Files',
                'View Files',
                'Select Agence',
                'Edit Account Settings',
            ],
            'Direction Author' => [
                'Create Dossier_Justice',
                'Edit Dossier_Justice',
                'Delete Dossier_Justice',
                'Preview Dossier_Justice',
                'List Dossier_Justice',
                'Create Partie_Adverse',
                'Edit Partie_Adverse',
                'Delete Partie_Adverse',
                'List Partie_Adverse',
                'Preview Partie_Adverse',
                'Create Audience',
                'Edit Audience',
                'Delete Audience',
                'List Audience',
                'Preview Audience',
                'Create Avocat',
                'Delete Avocat',
                'Edit Avocat',
                'Preview Avocat',
                'List Avocat',
                'Create Cour',
                'Edit Cour',
                'Delete Cour',
                'Preview Cour',
                'List Cour',
                'Create Files',
                'Delete Files',
                'Edit Files',
                'View Files',
                'Select Agence',
            ],
            'Direction Consultant' => [
                'Preview Dossier_Justice',
                'List Dossier_Justice',
                'List Partie_Adverse',
                'Preview Partie_Adverse',
                'List Audience',
                'Preview Audience',
                'Preview Avocat',
                'List Avocat',
                'Preview Cour',
                'List Cour',
                'View Files',
                'Select Agence',
            ],
            'Agence Admin' => [
                'Create Dossier_Justice',
                'Edit Dossier_Justice',
                'Delete Dossier_Justice',
                'Preview Dossier_Justice',
                'List Dossier_Justice',
                'Create Partie_Adverse',
                'Edit Partie_Adverse',
                'Delete Partie_Adverse',
                'List Partie_Adverse',
                'Preview Partie_Adverse',
                'Create Audience',
                'Edit Audience',
                'Delete Audience',
                'List Audience',
                'Preview Audience',
                'Create Avocat',
                'Delete Avocat',
                'Edit Avocat',
                'Preview Avocat',
                'List Avocat',
                'Create Cour',
                'Edit Cour',
                'Delete Cour',
                'Preview Cour',
                'List Cour',
                'Create User',
                'Edit User',
                'Delete User',
                'Preview User',
                'List User',
                'Create Files',
                'Delete Files',
                'Edit Files',
                'View Files',
                'Edit Account Settings',
            ],
            'Agence Author' => [
                'Create Dossier_Justice',
                'Edit Dossier_Justice',
                'Delete Dossier_Justice',
                'Preview Dossier_Justice',
                'List Dossier_Justice',
                'Create Partie_Adverse',
                'Edit Partie_Adverse',
                'Delete Partie_Adverse',
                'List Partie_Adverse',
                'Preview Partie_Adverse',
                'Create Audience',
                'Edit Audience',
                'Delete Audience',
                'List Audience',
                'Preview Audience',
                'Create Avocat',
                'Delete Avocat',
                'Edit Avocat',
                'Preview Avocat',
                'List Avocat',
                'Create Cour',
                'Edit Cour',
                'Delete Cour',
                'Preview Cour',
                'List Cour',
                'Create Files',
                'Delete Files',
                'Edit Files',
                'View Files',
            ],
            'Agence Consultant' => [
                'Preview Dossier_Justice',
                'List Dossier_Justice',
                'List Partie_Adverse',
                'Preview Partie_Adverse',
                'List Audience',
                'Preview Audience',
                'Preview Avocat',
                'List Avocat',
                'Preview Cour',
                'List Cour',
                'View Files',
            ],
            'Super Admin' => [
                'Create Dossier_Justice',
                'Edit Dossier_Justice',
                'Delete Dossier_Justice',
                'Preview Dossier_Justice',
                'List Dossier_Justice',
                'Create Partie_Adverse',
                'Edit Partie_Adverse',
                'Delete Partie_Adverse',
                'List Partie_Adverse',
                'Preview Partie_Adverse',
                'Create Audience',
                'Edit Audience',
                'Delete Audience',
                'List Audience',
                'Preview Audience',
                'Create Avocat',
                'Delete Avocat',
                'Edit Avocat',
                'Preview Avocat',
                'List Avocat',
                'Create Cour',
                'Edit Cour',
                'Delete Cour',
                'Preview Cour',
                'List Cour',
                'Create User',
                'Edit User',
                'Delete User',
                'Preview User',
                'List User',
                'Create Role',
                'Edit Role',
                'Delete Role',
                'List Role',
                'Preview Role',
                'Create Files',
                'Delete Files',
                'Edit Files',
                'View Files',
                'Select Agence',
                'Select Direction',
                'Edit Account Settings',
            ],
        ];

        foreach ($roles as $roleName => $permissions) {
            $role = DB::table('roles')->where('name', $roleName)->first();

            foreach ($permissions as $permissionName) {
                $permission = DB::table('permissions')->where('name', $permissionName)->first();

                DB::table('role_has_permissions')->insert([
                    'role_id' => $role->id,
                    'permission_id' => $permission->id,
                ]);
            }
        }
    }
    
}
